### ISSUE TITLE
Add "RESET TABLE" button

### ISSUE THREAD

**Issue by Azzhoe** [Ryan6578/TTS-Codenames#11]
This is to reload the table back to default, great for when the host/admin is AFK, and a promoted player can press this button to reload the table back to default incase there are any glitches.

**Comment by Ryan6578** [comment]
On second thought, this is something I would not like to include. I don't feel that it brings any noticeable value to the script. Hosts aren't supposed to be AFK, and the table should automatically reset on a new game.
