### ISSUE TITLE
Automated end turn doesn't always work

### ISSUE THREAD

**Issue by Azzhoe** [Ryan6578/TTS-Codenames#16]
Another issue is with the automated end turn feature. I notice at times whenever a team places the opposite color card down or a white card, that it should automatically end their turn. But it doesn't. I couldn't figure out the cause of this either.

**Comment by Ryan6578** [comment]
Are you sure this isn't due to the script not registering those card places? Increase the searchThreshold from 0.9 to 1 and see if you still get this.
