### ISSUE TITLE
Revamp voting process

### ISSUE THREAD

**Issue by Azzhoe** [Ryan6578/TTS-Codenames#17]
I have a few ideas on how we can improve on this: 

1. We can either have each player have infinite voting chips in their color, and they can use that to place over the word card to vote. Once the script detects all the players on the team  have voted on a word, it will check which agent card is suppose to go over that word and move it there and then destroy the chips.

or 

2. We can attach transparent buttons over the 25 word cards on the board using the alpha channel. It won't show up at all. But they are there for players to click on. So a player who wants to vote will physically click on the button, and the script will register the click and set a message in the note area (lower right side) showing which player has voted on which word, and which player hasn't voted yet, all dynamically. Once the script detects that all players on the team have settled on 1 word, it will go to the next logical step.

**Comment by Ryan6578** [comment]
Maybe defer to a different milestone, but we need more investigation into this.

**Comment by Ryan6578** [comment]
Requires more thought. If anyone has any ideas in order to implement this, I'm all ears.

**Comment by Ryan6578** [comment]
Decided not to implement. No clear way to do this. Doesn't add any value to the game, as it takes away from interactability.
