### ISSUE TITLE
Allow codemasters start a new game

### ISSUE THREAD

**Issue by Eggslaws** [Ryan6578/TTS-Codenames#2]
I wouldn't call it a issue but more of a feature request. Rather than letting promoted players do it, let Codemasters who are sat on Red & Blue to start a new game. The control for a new game is particularly on 624, but I don't really see a problem in giving control of the panel to the codemasters.

583, 591, 599, 607 and 615

**Comment by Ryan6578** [comment]
Fixed by pull request #3 .
