### ISSUE TITLE
Issue with latest update

### ISSUE THREAD

**Issue by ktnegativenancy** [Ryan6578/TTS-Codenames#28]
When a code master wants to tell their team to avoid a word while giving them infinite guesses they use the number 0. The new update that relates to turns ending automatically by using the equation (number of guesses + the one bonus guess) works for well for every number of guesses listed except when the code master uses 0. It lets them have 1 guess and then turn ends.

**Comment by Eggslaws** [comment]
So, I think there are two edits required here:

Line 472 for the function clue playback.
You may have to line at the validation part - something along the lines of:

if number == 0 then
message = "The " .. team .. " team's code is to avoid " .. clue .. ", with infinite guesses."


Then at Line 413, where you just need a If-Else if the number == 0?

**Comment by Ryan6578** [comment]
In cluemasterEncode():

```
elseif number == "0" then
  guessesLeft = -1
```

In playClue():

```
elseif number == "0" then
  message = ...
```

**Comment by Eggslaws** [comment]
I'm going to start referring to the functions, like professionals instead of referring to line numbers like noobs! I'm learning so much about coding here...
