### ISSUE TITLE
Turntracker bug

### ISSUE THREAD

**Issue by Eggslaws** [Ryan6578/TTS-Codenames#29]
Not sure if it was meant to be this way but while looking for something else, I came across the line 394 in the latest commit:

`if (playerColor == "Blue" and turnTracker == 0) or (playerColor == "Red" and turnTracker == 1) then`

Does it mean, Red can add a code when the turn tracker is 1 but Blue can't do so?

**Comment by Ryan6578** [comment]
When `turnTracker == 0`, it's red's turn. When `turnTracker == 1`, it's Blue's turn.

This statement ensures that Red can't encode on Blue's turn, and vice versa.

**Comment by Eggslaws** [comment]
That stops me from reporting another bug - lol - was almost in the middle of composing one.

btw, then what allows Red to type infinite clues on their turn but doesn't allow Blue to do so?

**Comment by Ryan6578** [comment]
Infinite as in the quantity of clues? Or infinite as in the content of the clue?

**Comment by Eggslaws** [comment]
quantity

**Comment by Ryan6578** [comment]
Nothing. I don't want to limit the number of clues codemasters can give. This is also a design choice. If they misspell something, and they wanted to re-encode, they wouldn't be able to if I limited the clues they could make per turn.

**Comment by Eggslaws** [comment]
Agreed. But blue has a clue limit of one per turn though. You might want to change that. I'm not able to find that line that does it.

**Comment by Ryan6578** [comment]
That shouldn't be the case, but I'll verify when I have the chance. Are you using the most up-to-date vanilla version of the script (no modifications made by you or others)?

**Comment by Eggslaws** [comment]
In Azzhoe's room. I'm assuming he is using the latest one from GitHub. I'm not promoted so not able to see the script version that is in use.

And you possibly may be right - I did see an error at the first time I tested after posting this but can't repro the issue even though I've been trying for the last 15-20 min.

**Comment by Ryan6578** [comment]
Yeah. I can't be sure of what he's incorporating and leaving out of his table from my script. I know he made some changes for a few minor features, but I can't make any guarantees for any versions other than my own.
