### ISSUE TITLE
Don't allow 'Shuffle Keymap' button to be pressed while game is in progress

### ISSUE THREAD

**Issue by Azzhoe** [Ryan6578/TTS-Codenames#36]
I noticed some trolls who sit as spymaster like to press this button while the game is in progress. Could it only work when a game isn't in progress?

**Comment by Ryan6578** [comment]
This wouldn't be possible. You would only need to shuffle the keymap during the game. I don't see a scenario where you would need to shuffle the keymap outside of a game. The game hasn't started yet and pushing the "New Game" button would do this anyway.

**Comment by Eggslaws** [comment]
What in case one of the Codemasters go nuts and click that button mid-game?

I see very less use of that button anyway - do we really need it??

**Comment by Eggslaws** [comment]
Suggest you could comment that section - anyone who would need it could enable it?
