### ISSUE TITLE
Allow In-Game Definition of Words

### ISSUE THREAD

**Issue by Ryan6578** [Ryan6578/TTS-Codenames#37]
Write against an API that delivers word definitions in game.

**Comment by Azzhoe** [comment]
Do you mean a feature that will allow the spymasters to look up meaning of words? If so, then this feature would be very handy. There's often times when spymasters do not know the meaning of a particular word. Having an easy way for red/blue to look up definitions in game perhaps via onchat commands or something would be beneficial.

**Comment by Ryan6578** [comment]
Not just codemasters. Anyone, really. There's lots of people who don't speak English as a first language that would benefit from this. Note that this would only be for dictionary words. Names and places wouldn't be included in this. Only words included in the dictionary.

**Comment by Ryan6578** [comment]
Invalidated. Doesn't provide much value.
