### ISSUE TITLE
a way for spymasters to get a list of all their words

### ISSUE THREAD

**Issue by Azzhoe** [Ryan6578/TTS-Codenames#38]
After a new round starts, the spymasters will each get a list of their words displayed to them somehow, so they can easily reference them. This makes it faster for them to connect their words and less likely to make mistakes.

Of course only the spymasters can see their list of words only.

**Comment by Eggslaws** [comment]
I've been thinking about that ever since some sent the link for the VR mobile app.

I suppose the way you do it would be to have a mostly transparent overlays over the words that won't rotate?

Or use a slightly large overlays that just borders the word tile but won't rotate? This of course would have to be hidden so the rest of them can't see it.

**Comment by Ryan6578** [comment]
This would require naming every single card in the decks to be entered into the Name field for each card. 400 words for the vanilla deck, 500 for Saydi's, 500 for Mayor's, 1100 for Hanii's, etc. You can see how this could get a little tedious after a while. I like the idea, but it just seems a little impractical. I can certainly look into this, as I think it would add value to the mod, but there has to be a better way to do this.

**Comment by Ryan6578** [comment]
Cards named via a script Hanii made. Words will be listed with an on-screen GUI element.

**Comment by Azzhoe** [comment]
I did a quick mockup to show what this may look like for the spymasters only. We can even do away and get rid of the keymap completely to give the table more space and make it cleaner. The words will also show up on some sort of UI or object and be visible to the spymasters only as well. (I didn't have time to mock that in this image). This would have to be done using the UI xml method. I believe you can attach UI elements to objects. So the colored rectangles would sit under the cards themselves.

![mockup1](https://user-images.githubusercontent.com/38174330/48603114-f9048c80-e93a-11e8-8fd6-d0b1e63eb9cb.jpg)

**Comment by Ryan6578** [comment]
Closing old issue that has already been implemented.
