### ISSUE TITLE
Clue box keeps focus after the clue is entered

### ISSUE THREAD

**Issue by Eggslaws** [Ryan6578/TTS-Codenames#40]
The box where Codemasters type the clue holds focus even after the clue is entered. If they don't notice and press C to talk, the box is filled with C's. If they want to chat, the box throws an error every time a space is entered due to validation rules. It is a slight annoyance to remember to click outside after entering the clue.

Wondering if there a way to do it automatically

**Comment by Ryan6578** [comment]
I can look into this to be 100% sure, but I'm fairly certain this isn't possible, as it's a limitation of TTS.

**Comment by Eggslaws** [comment]
Agreed. But it's Lua end of the day and I'm sure there should be a way to shift focus to another object in the table at the end of performing an action. Wondering if we change that focus to say the assassin card for example, does pressing C/Enter do the functions they are supposed to do?

**Comment by Ryan6578** [comment]
The only button that has this affect as far as I know is tab. Tab allows you to switch focus to another text box, but the issue would still occur.
