### ISSUE TITLE
Player-Level Statistics

### ISSUE THREAD

**Issue by Ryan6578** [Ryan6578/TTS-Codenames#51]
Expand the functionality of the analytics to support more detailed statistics (at the player level). Possibly implement a ranking system to give a rough estimate of the player's skill level (codemaster and player).

**Comment by HippoPenguin** [comment]
If this is implemented then analytics should be turned off by DEFAULT! also should allow individual users to turn off their own personal analytics if the host has turned on the game analytics. As there is no way a user can choose to have it on/off on an individual level or even know if they aren't savvy

**Comment by Ryan6578** [comment]
I'm collecting game information, not banking or credit card information. It's no different from any other game. League of Legends, Overwatch, Call of Duty, etc. They all collect this type of information and more. The script warns people if they join (and analytics are on) that the game is recorded and processed. If they don't want it that way, they are free to host their own lobby with analytics turned off. I don't see this as being much of a privacy issue, as there is no personally identifiable information other than a Steam64 ID and an IP address (to prevent stat forging). Unless you can give me a verifiable reason why this is an invasion of privacy (even with the warning of it being recorded), I don't see a basis for an argument here.
