### ISSUE TITLE
Additional Game Settings: Auto Start next round option (togglable) / Random Deck (togglable)

### ISSUE THREAD

**Issue by Azzhoe** [Ryan6578/TTS-Codenames#52]
I was thinking to add an "Auto Start Next Round" option to the settings control panel with ability to set the time in seconds on when it should initiate. This way you can specify a time that will initiate a new game to start. This should be a togglable on/off option. 

Example, you can set the amount of time in seconds that will initiate a new game to automatically start. I think this will better help the flow of the game.

---

Random Deck should also be a togglable option to allow every new round to start with a random deck if enabled.

**Comment by Ryan6578** [comment]
Not sure if I should do this. More decks loaded in means more lag for people joining the game. So, if we have all the decks loaded in, it might take people with crappy connections ages to load all the card assets.

**Comment by Eggslaws** [comment]
I for one would down vote the auto start of next round just to give the codemasters enough time to discuss their clues before starting the next round.

**Comment by Ryan6578** [comment]
Well, the round would start after a configurable amount of time, presumably. It would be a checkbox with an associated ticker to specify a number of seconds to start a game after (unless a new game is initiated before the game auto-starts).

**Comment by Azzhoe** [comment]
> I for one would down vote the auto start of next round just to give the codemasters enough time to discuss their clues before starting the next round.

That's why I mentioned to have this as a "Toggable" option for those who would like it can have it on and for others such as yourself can have it off. However, this can be looked both ways as it can help speed up the game. I've encountered games where people just go off topic after a round and takes ages to start a new round. This would alleviate that issue. So I think having this as a part of the game option would be nice. And since it will be an on/off feature, it shouldn't affect the core gameplay at all.

**Comment by Ryan6578** [comment]
Doesn't provide much value.
