### ISSUE TITLE
Feature to allow spymasters to see which cards on the table belong to which color group (Red, Blue, Black, White)

### ISSUE THREAD

**Issue by Azzhoe** [Ryan6578/TTS-Codenames#53]
With the latest update of TTS (10.9) that just came out. I noticed some new scripting additions that could finally make this possible. I saw this from the changelog:

- setHiddenFrom(players) Hides objects from a specific player/players. Uses "hand zone" hiding.
- setInvisibleTo(players) Hides objects from a specific player/players. Uses "hidden zone" hiding.
- attachHider(...) and attachInvisibleHider(...) are more advanced version of
- setHiddenFrom and setInvisibleTo, there to help handle complex situations easily.

https://api.tabletopsimulator.com/object/#setinvisibleto

Perhaps with these new LUA scripting additions, it would be possible to show which color a particular word card belongs to (WHITE, BLACK, RED, BLUE) perhaps having a subtle border around the card that only the spymasters can see. This would be a great visual cue for the spymasters and decrease the likelihood in placing the wrong agent card over the incorrect word.

I'm also sure these updated scripting functions can also help in hiding things with greater control from certain players or playercolor without using those ugly hidden zones.

**Comment by Ryan6578** [comment]
I think this might be useful for lots of other aspects of the mod as well. I'm going to do some preliminary exploration into this and include this in the scheduled 2.0.0 release.

**Comment by Ziboo** [comment]
I really like the idea but I think it should be an option...
The game also rely a lot on the spymaster sometime not seeing every cards or forgetting where are his card.
So by adding that I think you kind of break the game.

**Comment by Ryan6578** [comment]
The game shouldn't be to just hope the other codemaster makes a mistake. I think the gameplay should be easy, straightforward, and fair. That being said, I have already made this change. The rules are there in the case that the codemaster does make a mistake, but even with this change, people still do make mistakes. Not everyone is perfect. Just outplay your opponent. ;)
