### ISSUE TITLE
2 Player mode (Enhancement)

### ISSUE THREAD

**Issue by Eggslaws** [Ryan6578/TTS-Codenames#56]
I propose a check box/button to toggle to 2 player/3 player mode, that performs the following

1)  Disables the script to seat two codemasters but instead lets only one code master either for blue or red team (ideally for the team that has 9 words)

2) Disables the script from passing turns to the second team on guessing the wrong words/other team's words

3) Sets a timer for the whole game instead of resetting the timer for each turn.

This is NOT a mode for Codenames Duet but enables the game to be played when there are only 2-3 people waiting for more in a lobby.

Edit: Wondering how Codenames Statistics for a 2/3p game would work...

**Comment by Ryan6578** [comment]
I don't think this would add much value to the mod. Perhaps I can do something like this later down the road, but for now not something that is on the radar.
