### ISSUE TITLE
Separate Encoding Schemas for Codemasters

### ISSUE THREAD

**Issue by Ryan6578** [Ryan6578/TTS-Codenames#6]
Each codemaster should have his/her own encoding platform in front of them in a hidden area. This includes a text box and an encoding button (possibly a counter to denote the clue number). Teams will not be able to view the clue until it has been encoded. The clue will be transformed to uppercase so that case does not matter.

**Comment by Ryan6578** [comment]
For regex, @rjg88? I'm not sure that would work.

**Comment by Ryan6578** [comment]
This regex would roughly work I would think:

`.+[\s|-][0-9]+`

**Comment by rjg88** [comment]
LUA doesn't support regex, they are "patterns"

**Comment by Ryan6578** [comment]
Ahh. At that point, I'd rather just write my own validation. LOL
