### ISSUE TITLE
Table Redesign

### ISSUE THREAD

**Issue by Ryan6578** [Ryan6578/TTS-Codenames#66]
Out with the old, in with the new. Get rid of the ugly space theme and replace it with a cleaner-looking and more asthetically-pleasing alternative. In order to do this, I'd need to find a person with the following skills:

- Graphic design
- Photoshop proficiency
- Unity modeling
- Blender modeling [optional]

Create new textures and assets for the following:

- Room background
- Table background
- Panel backgrounds
- Agent cards
- Clue tiles

**Comment by ChildishGiant** [comment]
I may be of assistance but maybe not

- Gimp/Paint.net proficiency
- Unity proficiency
- Blender proficiency
