### ISSUE TITLE
When players switch seats too quickly it errors out and breaks the script

### ISSUE THREAD

**Issue by Azzhoe** [Ryan6578/TTS-Codenames#67]
I've experienced this a few times and have others player reported that this happens on all tables. When a player switch seats very quickly in rapid succession, it will throw off the seating panel. Even though the player has switch to grey, it still shows them as seated as a color and are able to interact with objects on the table. Not sure if this is a TTS issue or related to the script. 

Error in Script (Global) function onPlayerChangeColor: The given key was not present in the dictionary.

**Comment by Ryan6578** [comment]
Can you give me a list of steps you take that can reproduce this?

**Comment by Azzhoe** [comment]
Let me try to recall from the latest incident that was just reported to me by a player. They quickly change seats by pressing the buttons on the seating panel in rapid succession, and then I believe the error message came up. I had to reload the table to fix it. Try clicking randomly on all the colors but very quickly and eventually the message should show up.

**Comment by Ryan6578** [comment]
Haven't been able to reproduce. If you can show me how you do this, I'd be more than happy to reopen, but I haven't heard of this happening with anyone else either.
