### ISSUE TITLE
End Game Detection and Answers

### ISSUE THREAD

**Issue by Ryan6578** [Ryan6578/TTS-Codenames#7]
Detect end game scenario and respond by moving any remaining agent cards to their respective codes.

**Comment by rjg88** [comment]
Are we sure we want this feature?

Often times if the opposing team hits black, I like to see if my team would have understood the next clue I had in mind.

**Comment by Azzhoe** [comment]
Making this toggable instead of having it automated would be nice. Like assign it to a button on the cPanel. Whenever either spymasters are ready, they can press the button and let the cards move over the right words.
