### ISSUE TITLE
Busyness chart like Google Places or Facebook Places

### ISSUE THREAD

**Issue by brisdaz** [Ryan6578/TTS-Codenames#71]
![image](https://user-images.githubusercontent.com/50305553/57201186-ca599b80-6fd8-11e9-99ad-9f5581e1635d.png)

You record everytime a game starts or ends. So would it be possible to have a busyness chart like the above with the chart adjusted to like local timezone.

**Comment by Ryan6578** [comment]
Have a query written for this that will generate something like this with data averaged over the previous 30 days. I'll try to include it when I redo a bunch of the stats. Still collecting player stats, but haven't actually finished the website portion of it.
