### ISSUE TITLE
Codemaster confirms clue

### ISSUE THREAD

**Issue by emptyxd111** [Ryan6578/TTS-Codenames#75]
Hey,
would be cool if it would be possible if there was an option  that the other codemaster needs to confirm the clue before it is shown to the table :)
maybe with an option to turn it off/on

thanks alot
great script <3

**Comment by Ryan6578** [comment]
Will do some more investigation into whether or not this is a highly-requested or desired feature. Not sure if this would be a benefit to the greater Codenames community.
