### ISSUE TITLE
Option to disable background particles?

### ISSUE THREAD

**Issue by GarlicToum** [Ryan6578/TTS-Codenames#76]
We think the background particles cause the game to run slowly on some lower end systems. Any idea if it is the particles or something else that is slowing down the game?

Also, great job with the script, we've had a really good time playing!

**Comment by Ryan6578** [comment]
Good idea. I'm always looking for ways to optimize the script, and this would be a nice way to. I'll include it in the next release. Thanks! :)

**Comment by Ryan6578** [comment]
Implemented. Also added the ability to disable the ambient table lighting.
