### ISSUE TITLE
If a card is placed on top of a card on the table, it becomes unselectable

### ISSUE THREAD

**Issue by deansheather** [Ryan6578/TTS-Codenames#81]
Reproduction instructions:
1. Take a card from the deck
2. Flip it so light side is up
3. Place it on top of any card in play
4. Pull it away and place it to the side

The card in play loses its color and becomes unselectable by players.  If the card in play was a blue or red card, that team cannot win the game.

Pan is broken in this case. It was originally red, but no players can pick it anymore:
![screenshot](https://cdn.discordapp.com/attachments/304770111447760896/754197200707387412/unknown.png)

**Comment by Ryan6578** [comment]
Hi deansheather!

This has already been fixed in a beta version of the mod.

The new release doesn't have physical decks anymore, but rather pulls words from a web API. Grouped cards will automatically reset in this next version.

Thanks for reporting! :)
